_schema:
  name:
    type: String
    required: name is required
  description: String
  location: Object
  preferences: Object
  status:
    type: String
    default: unattended
  isActive:
    type: Boolean
    default: true
_options:
  timestamps: true
