_schema:
  name: String
  surname: String
  username: String
  email:
    type: String
    required: true
  password:
    type: String
    required: true
  favorites:
    type: String
    ref: Favorites
  studentId: String
  settings: Object
_options:
  timestamps: true
